# Generated by Django 5.0.3 on 2024-03-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200)),
                ('member_name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('no_of_rental', models.CharField(max_length=200)),
            ],
        ),
    ]
