# Generated by Django 5.0.3 on 2024-03-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issued',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_BookId', models.IntegerField()),
                ('issue_BookTitle', models.CharField(blank=True, max_length=200)),
                ('issue_BookAuthor', models.CharField(blank=True, max_length=200)),
                ('issue_BookIsbn', models.IntegerField()),
                ('issue_MemberId', models.IntegerField()),
                ('issue_MemberName', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='members',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='members',
            name='no_of_rental',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='members',
            name='reference_id',
            field=models.IntegerField(),
        ),
    ]
