# Generated by Django 5.0.3 on 2024-03-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_book_issued_alter_book_authors_alter_book_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issued',
            name='issue_BookAuthor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book_issued',
            name='issue_BookTitle',
            field=models.CharField(max_length=200),
        ),
    ]
