# Generated by Django 5.0.3 on 2024-03-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_book_issued_issue_bookauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issued',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
