# Generated by Django 5.0.3 on 2024-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_book_issued_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issued',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
