# Generated by Django 5.0.3 on 2024-03-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_book_issued_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issued',
            name='rent_fee',
            field=models.IntegerField(default=0),
        ),
    ]
