# Generated by Django 5.0.3 on 2024-03-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_issued_rent_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issued',
            name='total_debt',
            field=models.IntegerField(default=0),
        ),
    ]
