# Generated by Django 5.0.3 on 2024-03-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_book_issued_total_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_issued',
            name='fine',
        ),
    ]
