# Generated by Django 5.0.3 on 2024-03-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_book_issued_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_issued',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
