# Generated by Django 5.0.3 on 2024-03-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_book_issued_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issued',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
